# Generated by Django 5.1.1 on 2024-09-21 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodmemoapp", "0002_imagemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagemodel",
            old_name="is_roatated",
            new_name="is_rotated",
        ),
    ]
